version: "3"
services:
  # gateway
  gateway:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  # personal blog
  garyyou.com:
    image: garyyou.com:latest
    # depends_on:
      
    # - db
    # environment:
    #   DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080" # for the traffic from host to container

  # # paula's blog
  # paula_blog:
  #   image: paulas_website:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
#   db:
#     image: postgres:15.2-alpine
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - db:/var/lib/postgresql/data

# volumes:
#   db:
#     driver: local
