name: Rust Build & Test & Deploy
run-name: 🚀 Build & Test on ${{ github.sha }} by ${{ github.actor }}
on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test & Publish on ${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Publish to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.MY_DOCKER_USERNAME }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}

  deploy:
    name: Deploy ${{ github.sha }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_AWS_SERVER_HOST }}
          username: gary
          key: ${{ secrets.MY_AWS_SERVER_PRIVATE_KEY }}
          script: |
            cd ~
            ls
